[package]
name = "tokio-postgres"
version = "0.5.1"
authors = ["Steven Fackler <sfackler@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
description = "A native, asynchronous PostgreSQL client"
repository = "https://github.com/sfackler/rust-postgres"
readme = "../README.md"
keywords = ["database", "postgres", "postgresql", "sql", "async"]
categories = ["database"]

[lib]
test = false

[[bench]]
name = "bench"
harness = false

[package.metadata.docs.rs]
all-features = true

[badges]
circle-ci = { repository = "sfackler/rust-postgres" }

[features]
default = ["runtime"]
runtime = ["tokio/net", "tokio/time"]

with-bit-vec-0_6 = ["postgres-types/with-bit-vec-0_6"]
with-chrono-0_4 = ["postgres-types/with-chrono-0_4"]
with-eui48-0_4 = ["postgres-types/with-eui48-0_4"]
with-geo-types-0_4 = ["postgres-types/with-geo-types-0_4"]
with-serde_json-1 = ["postgres-types/with-serde_json-1"]
with-uuid-0_8 = ["postgres-types/with-uuid-0_8"]

[dependencies]
ntex = "0.5.6"
# bytes = { version = "0.1.8", package = "ntex-bytes" }
byteorder = "1.4"
fallible-iterator = "0.2"
futures = "0.3.13"
log = "0.4"
percent-encoding = "2.0"
pin-project-lite = "0.2"
phf = "0.8"
postgres-protocol = { version = "0.5.0", path = "../postgres-protocol" }
postgres-types = { version = "0.1.0", path = "../postgres-types" }
tokio = { version = "1", default-features = false }

[dev-dependencies]
tokio = { version = "1" }
ntex = { version = "0.5.6", features = ["tokio"] }
env_logger = "0.8"
criterion = "0.3"

bit-vec-06 = { version = "0.6", package = "bit-vec" }
chrono-04 = { version = "0.4", package = "chrono" }
eui48-04 = { version = "0.4", package = "eui48" }
geo-types-04 = { version = "0.4", package = "geo-types" }
serde-1 = { version = "1.0", package = "serde" }
serde_json-1 = { version = "1.0", package = "serde_json" }
uuid-07 = { version = "0.7", package = "uuid" }
uuid-08 = { version = "0.8", package = "uuid" }
